---

####################
# Create S3 using Terraform
####################

- name: Create the physical S3
  shell: |
    cd ../
    mkdir -p build/
    cp -r tf/* build/
    cd build/
    VARS_FILE="tfvars.sh"
    if [ -f $VARS_FILE ]; then
      echo "File $VARS_FILE exists."
      . ./$VARS_FILE
      terraform init -reconfigure -backend=true -get=true -input=false \
      -backend-config="bucket=449074299682-${TF_VAR_stack_name_prefix}-${TF_VAR_environment}-state-store" \
      -backend-config="region=${TF_VAR_region}" \
      -backend-config="key=terraform_states/s3-${TF_VAR_bucket_name}/terraform.tfstate"
      terraform apply -input=false -auto-approve > apply.txt
    else
      echo "File $VARS_FILE does not exist."
      exit 255
    fi